/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register.route'
import { Route as LogoutRouteImport } from './routes/logout.route'
import { Route as LoginRouteImport } from './routes/login.route'
import { Route as EditorRouteImport } from './routes/editor.route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RegisterRouteRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRouteRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const EditorRouteRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRoute
  '/login': typeof LoginRouteRoute
  '/logout': typeof LogoutRouteRoute
  '/register': typeof RegisterRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRoute
  '/login': typeof LoginRouteRoute
  '/logout': typeof LogoutRouteRoute
  '/register': typeof RegisterRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRoute
  '/login': typeof LoginRouteRoute
  '/logout': typeof LogoutRouteRoute
  '/register': typeof RegisterRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/login' | '/logout' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/login' | '/logout' | '/register'
  id: '__root__' | '/' | '/editor' | '/login' | '/logout' | '/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRouteRoute: typeof EditorRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  LogoutRouteRoute: typeof LogoutRouteRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRouteRoute: EditorRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  LogoutRouteRoute: LogoutRouteRoute,
  RegisterRouteRoute: RegisterRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor",
        "/login",
        "/logout",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/editor": {
      "filePath": "editor.route.tsx"
    },
    "/login": {
      "filePath": "login.route.tsx"
    },
    "/logout": {
      "filePath": "logout.route.tsx"
    },
    "/register": {
      "filePath": "register.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
